name = "SFF"
author = "Khorne"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e761cba53067980b8294ceb55cf93f5c4c178c1c4cfe79553423f25ccaa41eef"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
